### ISSUE TITLE
rig-remote should be able to connect to more than one rig at the same time.

### ISSUE THREAD

**Issue by Marzona** [Marzona/rig-remote#24]
There are more than one use-case for this feature.
As an user I may want to tune more than one frequency at the time:
- [ ] I want to listen a full duplex conversation: a full duplex conversation that involves 2 frequencies and potentially two different modes. As an example I may want to listen to airplane<->airport communication.

As an user I may want to use more than one rig for scanning a wide range of frequency:
- [ ] the average SDR dongle is able to tune a wide range of frequency. Given a frequency range I may want to use rig-remote to monitor or scan that range splitting it in parts and use one rig for scanning a single part. This would halve the time for a complete scan (with autobookmark) ... or a more effective monitoring.

The above features imply some side-related changes in the tool:
- [ ] re-design the bookmarks implementation.see https://github.com/Marzona/rig-remote/issues/26
- [ ] The UI needs to be heavily lifted for accommodating the panels for the rig after the first one. see https://github.com/Marzona/rig-remote/issues/27
- [ ] we may want to provide also https://github.com/Marzona/rig-remote/issues/28

**Comment by Marzona** [comment]
the codechange that handles 2 rigs is committed in :
411ef22bdce5487ebd6a156cc9023de2b7c6b9a8

#26. #27 and #28 are open and need to be tackled.
